CREATE DATABASE Zizo_Papelaria

USE Zizo_Papelaria

CREATE TABLE `CLIENTE` (
  `ID_CLIENTE` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` varchar(100) DEFAULT NULL,
  `DATA_NASC_CLIENTE` date DEFAULT NULL,
  `EMAIL_CLIENTE` varchar(100) DEFAULT NULL,
  `TELEFONE` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`ID_CLIENTE`)
)

CREATE TABLE `COMPRA` (
  `ID_COMPRA` int(11) NOT NULL AUTO_INCREMENT,
  `VALOR_TOTAL` decimal(10,2) DEFAULT NULL,
  `DATA_COMPRA` date DEFAULT NULL,
  PRIMARY KEY (`ID_COMPRA`)
)

CREATE TABLE `FORNECEDOR` (
  `ID_FORNECEDOR` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_FORNECEDOR` varchar(100) DEFAULT NULL,
  `EMAIL_FORNECEDOR` varchar(100) DEFAULT NULL,
  `TELEFONE_FORNECEDOR` varchar(12) DEFAULT NULL,
  `CNPJ_FORNECEDOR` varchar(14) DEFAULT NULL,
  PRIMARY KEY (`ID_FORNECEDOR`)
)

CREATE TABLE `PRODUTO` (
  `ID_PRODUTO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME_PRODUTO` varchar(100) DEFAULT NULL,
  `PRECO_UNITARIO` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUTO`)
)

CREATE TABLE `VENDA` (
  `ID_VENDA` int(11) NOT NULL AUTO_INCREMENT,
  `VALOR_TOTAL` decimal(10,2) DEFAULT NULL,
  `DATA_VENDA` date DEFAULT NULL,
  `ID_CLIENTE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_VENDA`),
  KEY `fk_venda` (`ID_CLIENTE`),
  CONSTRAINT `fk_venda` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `CLIENTE` (`id_cliente`)
) 

CREATE TABLE `COMPRA_X_PRODUTOxFORNECEDORES` (
  `ID_COMPRA_X_PRODUTOxFORNECEDORES` int(11) NOT NULL AUTO_INCREMENT,
  `FK_PRODUTOxFORNECEDORES` int(11) DEFAULT NULL,
  `FK_COMPRA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID_COMPRA_X_PRODUTOxFORNECEDORES`),
  KEY `fk_produtoxfornecedores` (`FK_PRODUTOxFORNECEDORES`),
  KEY `fk_compra` (`FK_COMPRA`),
  CONSTRAINT `fk_compra` FOREIGN KEY (`FK_COMPRA`) REFERENCES `COMPRA` (`id_compra`),
  CONSTRAINT `fk_produtoxfornecedores` FOREIGN KEY (`FK_PRODUTOxFORNECEDORES`) REFERENCES `PRODUTO_X_FORNECEDORES` (`id_produto_fornecedores`)
)


CREATE TABLE `PRODUTO_X_FORNECEDORES` (
  `ID_PRODUTO_FORNECEDORES` int(11) NOT NULL AUTO_INCREMENT,
  `FK_PRODUTO` int(11) DEFAULT NULL,
  `FK_FORNECEDORES` int(11) DEFAULT NULL,
  `PRECO_UNITARIO` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`ID_PRODUTO_FORNECEDORES`),
  KEY `FK_FORNECEDORES_CONSTRAINT` (`FK_FORNECEDORES`),
  KEY `FK_PRODUTO_CONSTRAINT` (`FK_PRODUTO`),
  CONSTRAINT `FK_FORNECEDORES_CONSTRAINT` FOREIGN KEY (`FK_FORNECEDORES`) REFERENCES `FORNECEDOR` (`id_fornecedor`),
  CONSTRAINT `FK_PRODUTO_CONSTRAINT` FOREIGN KEY (`FK_PRODUTO`) REFERENCES `PRODUTO` (`id_produto`)
)